api = "0.8"
WithWindowsBuild = false
WithLinuxBuild = false

[buildpack]
  id = "traefik"
  version = "1.0.0"

[[targets]]
  os = "darwin"
  arch = "arm64"

[[targets]]
  os = "linux"
  arch = "arm64"

[[targets]]
  os = "linux"
  arch = "amd64"
